# SPDX-FileCopyrightText: Copyright © 2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: ai-engines
on: push
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions
      - run: corepack enable
      - run: yarn install --immutable
      - run: npm install -g @github/copilot @jetbrains/junie
      - run: yarn workspace @xenoterracide/ghb-merge run test
