# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT
name: precommit
on: [push, workflow_call]
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@f3c82147662e154713ca45808b4c0f5a2416f03d # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@f3c82147662e154713ca45808b4c0f5a2416f03d # develop
  node-cli:
    uses: xenoterracide/github/.github/workflows/node-cli.yml@f3c82147662e154713ca45808b4c0f5a2416f03d # develop
