# SPDX-FileCopyrightText: Copyright © 2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT
name: test
on: [push]
jobs:
  yarn:
    uses: xenoterracide/github/.github/workflows/yarn.yml@c4452b4d576a313a2b49ba915a97ff25745477ae # develop
