# SPDX-FileCopyrightText: Copyright © 2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT
name: test
on: [push]
jobs:
  yarn:
    uses: xenoterracide/github/.github/workflows/yarn.yml@552ed860c829e2253ccc24bf836cc732a12e8b9c # develop
